
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxwljcayrakzisfunksv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4d2xqY2F5cmFremlzZnVua3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTY5MzAsImV4cCI6MjA2MzI5MjkzMH0.L_oV7aUlcQYJgEp7vMpjSiXnJ-WZlqU7YjdlxptKYNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
